---
title: "CONGAS"
output: html_document
date: "2024-11-28"
---

```{r}
reticulate::use_condaenv("CONGAS", required = TRUE)
library(reticulate)
# devtools::load_all("~/work/r_packages/rcongas/")
```

```{r}
library(Rcongas)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}
library(Seurat)
```

```{r}
#read multiome data
multi <- Read10X("/group/sottoriva/00-PROCESSED_DATA/2023-ROVIGO/BTROHT01/BTROHT01/BTROHT01_T1_T7_T9/multiome/LAZ_160/filtered_feature_bc_matrix")
myrna_counts <- multi$`Gene Expression`
myatac_counts <- multi$`Peaks`
myatac_counts

# Replace ":" with "-" in the row names of the matrix
rownames(myatac_counts) <- gsub(":", "-", rownames(myatac_counts))

# Verify the result
head(rownames(myatac_counts))

typeof(multi)
myrna_counts
myatac_counts

```

```{r}


#/group/sottoriva/00-PROCESSED_DATA/2023-ROVIGO/BTROHT01/BTROHT01/BTROHT01_T1_T7_T9/multiome/LAZ_160/filtered_feature_bc_matrix.h5
mybarcode_list <- read.table("/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal/CONGAS/BTROHT01_peri_barcodes_all.tsv", sep="\t", header=TRUE)
mybarcode_list
mybarcode_values <- mybarcode_list$X


myrna_counts <- myrna_counts[, colnames(myrna_counts) %in% mybarcode_values]
myatac_counts <- myatac_counts[, colnames(myatac_counts) %in% mybarcode_values]
myatac_counts
myrna_counts
#myatac
#
```



```{r}
library(data.table)
# Read the gzipped TSV file
myfeatures <- fread("gunzip -c /group/sottoriva/00-PROCESSED_DATA/2023-ROVIGO/BTROHT01/BTROHT01/BTROHT01_T1_T7_T9/multiome/LAZ_160/filtered_feature_bc_matrix/features.tsv.gz")
new_names <- c("gene_id", "gene", "modality", "chr", "from", "to")
names(myfeatures) <- new_names
tail(myfeatures)
```
```{r}
#getwd()
#sample = "/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal"

#prefix = paste0(sample, "/CONGAS/")

#out.dir = paste0(prefix, "/congas_data/")
#fig.dir = paste0(prefix, "/congas_figures/")

#if (!dir.exists(out.dir)) {dir.create(out.dir, recursive = T)}
#if (!dir.exists(fig.dir)) {dir.create(fig.dir, recursive = T)}

```

```{r}
myatac_featureDF = data.frame(id = rownames(myatac_counts)) %>%
  tidyr::separate(id, c('chr', 'from', 'to'), '-')
myatac_featureDF

myfeatures
```

```{r}
myatac = Rcongas::create_congas_tibble(counts = myatac_counts, 
                                     modality = 'ATAC', 
                                     save_dir = NULL,
                                     features = myatac_featureDF)
myatac <- na.omit(myatac)



#mybarcode_list
#mybarcode_values <- mybarcode_list$X

```

```{r}
library(dplyr)

# Step 1: Filter Barcodes in `barcode_list` that match `myatac$cell`
filtered_barcodes <- mybarcode_list %>%
  filter(X %in% myatac$cell)

# Step 2: Generate Metadata with "-ATAC"
metadata_atac <- filtered_barcodes %>%
  mutate(cell = paste0(X, "-ATAC"), type = UMAP.of.ATAC.in.BTROH01.Perimarginal) %>%
  select(cell, type)

# Step 3: Generate Metadata with "-RNA"
metadata_rna <- filtered_barcodes %>%
  mutate(cell = paste0(X, "-RNA"), type = UMAP.of.ATAC.in.BTROH01.Perimarginal) %>%
  select(cell, type)

# Step 4: Combine ATAC and RNA Metadata
mymetadata <- bind_rows(metadata_atac, metadata_rna)

# Step 5: View Summary
print(mymetadata)
tail(mymetadata)
# Optional: Save to a file if needed
# write.csv(metadata, "metadata.csv", row.names = FALSE)
mymetadata

```

```{r}
# Compute normalization factors
mynorm_atac = Rcongas:::auto_normalisation_factor(myatac) %>%
  mutate(modality = 'ATAC')

myrna = Rcongas::create_congas_tibble(counts = myrna_counts, 
                                    modality = 'RNA', 
                                    save_dir=NULL, 
                                    features = features)

# Compute normalization factors
mynorm_rna = Rcongas:::auto_normalisation_factor(myrna) %>%
  mutate(modality = 'RNA')

myatac = myatac %>% mutate(value = as.integer(value))
myrna = myrna %>% mutate(value = as.integer(value))
```

```{r}
myrna = myrna %>% filter_known_genes(what='r')
all_genes = myrna$gene %>% unique
mito = all_genes %>% str_starts(pattern = 'MT-')
all_genes = setdiff(all_genes, all_genes[mito])
myrna = myrna %>% dplyr::filter(gene %in% all_genes)
```

```{r}
mysegs <- read.csv("/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Core/CONGAS/BTROHT01_copre_segs_for_congas.csv", sep = "\t", row.names = 1)
mysegments = mysegs %>% dplyr::filter(chr != 'chrX', chr != 'chrY')
myatac

```



```{r}

myx = init(
  rna = myrna,
  atac = myatac,
  segmentation = mysegments, #%>% mutate(copies = as.integer(round(copies))),
  rna_normalisation_factors = mynorm_rna,
  atac_normalisation_factors = mynorm_atac,
  rna_likelihood = "NB", 
  atac_likelihood = "NB",
  description = paste0('Bimodal', "sample"),
  multiome = TRUE)

```

```{r}
getwd()
# Load necessary libraries
library(dplyr)

# Define the output file path
output_file <- "plot1.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed


#plot the number of nonzero cells vs the number of peaks per segment,
ggplot(myx$input$segmentation, aes(x=ATAC_nonzerocells, y=ATAC_peaks)) + geom_point() + theme_bw()
# Close the PDF device
dev.off()

# Print a message to confirm
cat("Plot saved to:", output_file)

```

```{r}

# Load necessary libraries
library(dplyr)

# Define the output file path
output_file <- "plot2.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed


ggplot(myx$input$segmentation, aes(x=RNA_nonzerocells, y=RNA_genes)) + geom_point() + theme_bw()
# Close the PDF device
dev.off()

# Print a message to confirm
cat("Plot saved to:", output_file)


```

```{r}
myx = Rcongas::filter_segments(myx, RNA_nonzerocells = 300, ATAC_nonzerocells = 300)
```


```{r}

# Load necessary libraries
library(dplyr)

# Define the output file path
output_file <- "countdistribution_RNA_ATAC.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed


plot_data(
  myx,
  what = 'histogram',
  segments = get_input(myx, what = 'segmentation') %>%
    ungroup() %>%
    mutate(L = to - from) %>%
    dplyr::arrange(dplyr::desc(L)) %>%
    dplyr::top_n(30) %>%
    pull(segment_id)
)

# Close the PDF device
dev.off()

# Print a message to confirm
cat("Plot saved to:", output_file)

```



```{r}
getwd()
# Load necessary libraries
library(dplyr)
mymetadata
myx$input$metadata = mymetadata
# Define the output file path
output_file <- "countdistribution_annotated.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed

# Plot the data
plot_data(
  myx, 
  to_plot = 'type', 
  position = 'stack',
  segments = get_input(myx, what = 'segmentation') %>%
    ungroup() %>%
    mutate(L = to - from) %>%
    arrange(desc(L)) %>%
    top_n(30) %>%
    pull(segment_id)
)

# Close the PDF device
dev.off()

# Print a message to confirm
cat("Plot saved to:", output_file)

myx
```
```{r}
library(Rcongas)
library(dplyr)
library(ggplot2)
library(stringr)
```

```{r}

filt = segments_selector_congas(myx)
# You can save the filtering result to avoid re-running the whole pipeline in future steps
# saveRDS(filt, paste0(out.dir, "rcongas_obj_filtered.rds"))
```
```{r}
# Set values fro the model hyperparameters
k = c(1:4)

binom_limits = c(40,1000)
model = "BIC"

lr = 0.01
temperature = 20

steps = 5000
lambda = 0.5

# Estimate hyperparameters
hyperparams_filt <- auto_config_run(filt, k, 
                                    prior_cn=c(0.2, 0.6, 0.1, 0.05, 0.05),
                                    init_importance = 0.6, 
                                    CUDA = FALSE, 
                                    normal_cells=TRUE)

# Run
hyperparams_filt$binom_prior_limits = binom_limits

fit_filt <- Rcongas:::fit_congas(filt,
                                 K = k, 
                                 lambdas = lambda, 
                                 learning_rate = lr, 
                                 steps = steps,
                                 model_parameters = hyperparams_filt, 
                                 model_selection = model,
                                 latent_variables = "G",
                                 CUDA = FALSE,
                                 temperature = temperature, 
                                 same_mixing = TRUE, 
                                 threshold = 0.001)

fit_filt
getwd()

saveRDS(fit_filt, "/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal/CONGAS/rcongas_obj_filtered_BTROHT01_peri_all_cells.rds")
```
```{r}
fit_filt$model_selection
```
```{r}

getwd()
# Define the output file path
output_file <- "fitplotb1peri.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed

Rcongas::plot_fit(fit_filt, what='scores')

dev.off()

```

```{r}

# Define the output file path
output_file <- "CONGAS_clusterb1peri.pdf"

# Open a PDF device
pdf(file = output_file, width = 12, height = 8)  # Adjust width and height as needed

plot_fit(fit_filt, 'posterior_CNA')

dev.off()

```

```{r}
getwd()
# Define the output file path
output_file <- "density_fitplotb1peri.pdf"

# Open a PDF device
pdf(file = output_file, width = 40, height = 20)  # Adjust width and height as needed

p = cowplot::plot_grid( 
  plotlist = plot_fit(fit_filt, what = 'density', highlights = TRUE),
  ncol = 30)
p
dev.off()
```

```{r}
# Adjust base width and height for individual plots in the plot list
plot_list <- plot_fit(fit_filt, what = 'density', highlights = TRUE)

# Resize the individual plots before passing them to cowplot::plot_grid
plot_list_resized <- lapply(plot_list, function(p) {
  p + theme(
    plot.margin = margin(5, 5, 5, 5),  # Adjust margins if needed
    plot.title = element_text(size = 10)  # Adjust title size if necessary
  )
})

# Now, use these resized plots in the grid
output_file <- "density_fitplotb1peri.pdf"
pdf(file = output_file, width = 40, height = 10)

p = cowplot::plot_grid(
  plotlist = plot_list_resized,
  ncol = 30  # Keep ncol as 30
)

# Print the plot and close the PDF device
p
dev.off()


```


```{r}

# Define the output file path
output_file <- "heatmap_b1peri.pdf"

# Open a PDF device
pdf(file = output_file, width = 50, height = 16)  # Adjust width and height as needed

plot_fit(fit_filt, what = 'heatmap',scale = TRUE , scale_min_lim = -2, scale_max_lim = 2)

dev.off()



```

```{r}
getwd()
saveRDS(fit_filt, "/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal/CONGAS/rcongas_obj_filtered_BTROHT01_peri_all_cells.rds")
```

```{r}
df <- data.frame(fit_filt$best_fit$CNA_real$cluster, fit_filt$best_fit$CNA_real$value, fit_filt$best_fit$CNA_real$segment_id)
df
getwd()
write.table(df, file = "/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal/CONGAS/ploidy_by_segments_BTROHT01_peri.tsv", sep = "\t", row.names = FALSE, quote = FALSE)
```

```{r}
write.csv(fit_filt$best_fit$cluster_assignments, file = "/home/fatemeh.nasrabadi/ROVIGO_congas/BTROHT01/Perimarginal/CONGAS/BTROHT01_peri_CONGAS_Clusters.csv", row.names = FALSE)
```



